# Generated by Django 5.1.3 on 2024-12-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emoAdmins', '0003_rename_email_teacher_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('assignment_file', models.FileField(upload_to='assignments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
