# Generated by Django 5.1.3 on 2024-12-06 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emoAdmins', '0004_assignment_delete_notice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='assignment_file',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='uploaded_at',
        ),
    ]
