# Generated by Django 5.1.3 on 2024-12-06 11:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emoAdmins', '0005_rename_assignment_file_assignment_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
