# Generated by Django 5.1.3 on 2024-12-06 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emoAdmins', '0007_remove_assignment_uploaded_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='Email',
            new_name='email',
        ),
    ]
