# Generated by Django 5.1.3 on 2024-12-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emoAdmins', '0009_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
