# Generated by Django 5.1.3 on 2024-12-07 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emoAdmins', '0010_questions_delete_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
