# Generated by Django 5.1.3 on 2024-11-30 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
    ]
