# Generated by Django 5.1.3 on 2024-12-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emoapp', '0004_surveyquestion_surveyresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('issue_type', models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('video', 'Video')], max_length=5)),
                ('text_message', models.TextField(blank=True, null=True)),
                ('audio_message', models.FileField(blank=True, null=True, upload_to='audio_issues/')),
                ('video_message', models.FileField(blank=True, null=True, upload_to='video_issues/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
